services:
  mysql:
    image: mysql:8.0
    container_name: ilajak-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./clinic.sql:/docker-entrypoint-initdb.d/clinic.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ilajak-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      APP_KEY: "base64:OCx04i80SF4ydDXjFpvCGAZsPUOckwxDEkC/Vs3xE3g="

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: clinic
      DB_USERNAME: root
      DB_PASSWORD: root

    command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
  mysql_data: